# Generated by Django 5.0.4 on 2024-04-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_order_address_order_contact_number_order_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="client",
            field=models.CharField(max_length=150),
        ),
    ]
