# Generated by Django 5.0.4 on 2024-04-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0004_alter_order_employee"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("при_получении", "При получении"), ("оплачено", "Оплачено")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
    ]
