# Generated by Django 5.0.4 on 2024-04-28 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_order_delivery_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["status", "-creation_time"],
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(
                help_text="Адрес доставки для этого заказа.",
                max_length=120,
                verbose_name="Адрес",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="client",
            field=models.CharField(
                help_text="Имя клиента, оформившего этот заказ.",
                max_length=150,
                verbose_name="Клиент",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="contact_number",
            field=models.CharField(
                help_text="Контактный номер клиента для связи.",
                max_length=25,
                verbose_name="Контактный номер",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="creation_time",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время создания этого заказа.",
                verbose_name="Дата создания",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="delivery_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Планируемая дата доставки этого заказа.",
                null=True,
                verbose_name="Дата доставки",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Дополнительное описание или комментарии к этому заказу.",
                max_length=10000,
                null=True,
                verbose_name="Описание",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                help_text="Пользователь, ответственный за выполнение этого заказа.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Исполнитель",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="name",
            field=models.CharField(
                help_text="Название этого заказа.",
                max_length=100,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("при_получении", "При получении"), ("оплачено", "Оплачено")],
                help_text="Выберите способ оплаты для этого заказа.",
                max_length=20,
                verbose_name="Способ оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Цена этого заказа.",
                max_digits=20,
                verbose_name="Цена",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.BooleanField(
                help_text="Статус выполнения этого заказа.", verbose_name="Статус"
            ),
        ),
    ]
