# Generated by Django 5.0.4 on 2024-05-01 20:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0007_alter_order_options_alter_order_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-creation_time"],
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
